# Generated by Django 4.2 on 2023-04-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cvinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                ("age", models.IntegerField(max_length=50, verbose_name="年龄")),
                ("xueli", models.CharField(max_length=20, verbose_name="最高学历")),
                ("school", models.CharField(max_length=20, verbose_name="毕业院校")),
                ("nianxian", models.IntegerField(max_length=50, verbose_name="工作年限")),
                ("major", models.CharField(max_length=20, verbose_name="专业")),
            ],
            options={
                "verbose_name": "简历信息",
                "verbose_name_plural": "简历信息",
                "db_table": "cv_info",
            },
        ),
    ]
