# Generated by Django 4.2 on 2023-04-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvtest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvinfo",
            name="age",
            field=models.IntegerField(verbose_name="年龄"),
        ),
        migrations.AlterField(
            model_name="cvinfo",
            name="nianxian",
            field=models.IntegerField(verbose_name="工作年限"),
        ),
    ]
