# Generated by Django 4.2 on 2023-04-18 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cvtest", "0002_alter_cvinfo_age_alter_cvinfo_nianxian"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvinfo",
            name="create_datetime",
            field=models.DateTimeField(
                auto_now_add=True, help_text="创建时间", null=True, verbose_name="创建时间"
            ),
        ),
        migrations.AddField(
            model_name="cvinfo",
            name="creator",
            field=models.ForeignKey(
                db_constraint=False,
                help_text="创建人",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="cvinfo",
            name="dept_belong_id",
            field=models.CharField(
                blank=True,
                help_text="数据归属部门",
                max_length=100,
                null=True,
                verbose_name="数据归属部门",
            ),
        ),
        migrations.AddField(
            model_name="cvinfo",
            name="description",
            field=models.CharField(
                blank=True, help_text="描述", max_length=100, null=True, verbose_name="描述"
            ),
        ),
        migrations.AddField(
            model_name="cvinfo",
            name="is_delete",
            field=models.BooleanField(
                blank=True, default=False, help_text="逻辑删除", verbose_name="逻辑删除"
            ),
        ),
        migrations.AddField(
            model_name="cvinfo",
            name="modifier",
            field=models.CharField(
                blank=True,
                help_text="修改人",
                max_length=100,
                null=True,
                verbose_name="修改人",
            ),
        ),
        migrations.AddField(
            model_name="cvinfo",
            name="update_datetime",
            field=models.DateTimeField(
                auto_now=True, help_text="修改时间", null=True, verbose_name="修改时间"
            ),
        ),
        migrations.AlterField(
            model_name="cvinfo",
            name="id",
            field=models.CharField(
                default=utils.models.make_uuid,
                help_text="Id",
                max_length=100,
                primary_key=True,
                serialize=False,
                verbose_name="Id",
            ),
        ),
    ]
