# Generated by Django 4.2 on 2023-06-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cvupload", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cvuploadinfo",
            options={"verbose_name": "简历上传信息", "verbose_name_plural": "简历上传信息"},
        ),
    ]
