# Generated by Django 4.2 on 2023-07-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvupload", "0002_alter_cvuploadinfo_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvuploadinfo",
            name="cv_img",
            field=models.CharField(default="", max_length=255, verbose_name="简历图片"),
        ),
    ]
