# Generated by Django 4.2 on 2023-07-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvupload", "0003_cvuploadinfo_cv_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvuploadinfo",
            name="cvlist",
            field=models.CharField(
                default="", max_length=255, verbose_name="所有简历图片URL"
            ),
        ),
        migrations.AlterField(
            model_name="cvuploadinfo",
            name="cv_img",
            field=models.CharField(default="", max_length=255, verbose_name="简历图片URL"),
        ),
    ]
