# Generated by Django 4.2 on 2023-07-13 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cvupload", "0004_cvuploadinfo_cvlist_alter_cvuploadinfo_cv_img"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cvuploadinfo", old_name="cvlist", new_name="cv_list",
        ),
    ]
