# Generated by Django 4.2 on 2023-08-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvupload", "0005_rename_cvlist_cvuploadinfo_cv_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvuploadinfo",
            name="post",
            field=models.CharField(
                blank=True, default="", max_length=60, null=True, verbose_name="推荐岗位"
            ),
        ),
    ]
