# Generated by Django 4.2 on 2023-08-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvupload", "0007_cvuploadinfo_match"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvuploadinfo",
            name="match",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True, verbose_name="岗位匹配度"
            ),
        ),
    ]
