# Generated by Django 4.2 on 2023-04-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cvpost", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="cvpostinfo", name="age",),
        migrations.RemoveField(model_name="cvpostinfo", name="is_delete",),
        migrations.RemoveField(model_name="cvpostinfo", name="major",),
        migrations.RemoveField(model_name="cvpostinfo", name="name",),
        migrations.RemoveField(model_name="cvpostinfo", name="nianxian",),
        migrations.RemoveField(model_name="cvpostinfo", name="school",),
        migrations.RemoveField(model_name="cvpostinfo", name="xueli",),
        migrations.AlterField(
            model_name="cvpostinfo",
            name="title",
            field=models.CharField(max_length=100, verbose_name="岗位名称"),
        ),
    ]
